### ISSUE TITLE
Bunch of errors

### ISSUE THREAD

**Issue by aldyahsn** [pol2095/Feathers-Extension-Canvas#1]
Hi. I would say thank you for your work. It is good alternative for Starling Graphics Class which is only support for Starling v1.x.

I tried adding simple graphics to screen class component with this code.
`var canvas:Canvas = new Canvas();
canvas.graphics.lineStyle(1, 0xFF0000);
canvas.graphics.moveTo(20, 20);
canvas.graphics.lineTo(100, 100);
canvas.graphics.lineTo(200, 100);
addChild(canvas);`

got 16 errors. Here are some descriptions:

1. _... feathers\extensions\canvas\CanvasControl.as:18:Error: Call to a possibly undefined method addEventListener through a reference with static type CanvasDisplayObject.

2. ...\feathers\extensions\canvas\CanvasDisplayObject.as:44:Error: Access of possibly undefined property antiAliasing.

3. ...\feathers\extensions\canvas\CanvasDisplayObject.as:89:Error: Call to a possibly undefined method getChildIndex through a reference with static type CanvasDisplayObject.

4. ...\feathers\extensions\canvas\CanvasDisplayObject.as:91:Error: Call to a possibly undefined method addChild.

5. ...\feathers\extensions\canvas\CanvasDisplayObject.as:124:Error: Method marked override must override another method._

**Comment by pol2095** [comment]
Sorry, I don't see your post, Canvas doesn't work with Starling 2.1 release, download the last starling update on [github](https://github.com/Gamua/Starling-Framework)

**Comment by aldyahsn** [comment]
Thanks for your reply. 

What don't you mean with "download last starling update" while on the otherhand Starling 2.1 doesn't support Canvas.

**Comment by aldyahsn** [comment]
Sorry typo
*Dont you = do you

**Comment by pol2095** [comment]
Download the zip file on GitHub (the green button "clone or download"), not the release.

**Comment by pol2095** [comment]
You can use [https://github.com/pol2095/Feathers-Extension-Canvas/tree/starling-2.1](https://github.com/pol2095/Feathers-Extension-Canvas/tree/starling-2.1)
